// Copia de interfaz. Los valores de releases, artists, home, about y blog
// son contenido editorial y no se modifican al cambiar de idioma.
export const UI_EN = {
  'Sin título': 'Untitled', 'sin número': 'no catalog number', 'oculto': 'hidden',
  'No se puede guardar. Falta:': 'Cannot save. Missing:', 'Pendiente:': 'Needs attention:',
  'el título': 'title', 'los artistas': 'artists', 'un artista que ya no existe': 'an artist who no longer exists',
  'la fecha': 'date', 'la carátula': 'cover image', 'el link para comprar': 'purchase link', 'los créditos': 'credits',
  'Lanzamiento': 'Release', 'El número de catálogo es opcional.': 'The catalog number is optional.',
  'La fecha aparece en los créditos.': 'The date appears in the credits.',
  'Oculto: se guarda, pero no aparece en el sitio.': 'Hidden releases are saved but do not appear on the site.',
  'Título': 'Title', 'Nº catálogo': 'Catalog no.', 'Fecha': 'Date', 'Visible en el sitio': 'Visible on the site',
  'Artistas': 'Artists', 'Busca para filtrar. Escribe un nombre nuevo para crearlo.': 'Search to filter, or enter a new name to create an artist.',
  'Edita un nombre desde su ficha.': 'Edit a name from its release.',
  'Corregir el nombre': 'Edit name', 'Quitar': 'Remove', '¿Cómo se escribe?': 'How should the name be written?',
  'Carátula y links': 'Cover and links',
  'La carátula se importa de Bandcamp. También puedes pegar su código.': 'The cover is imported from Bandcamp. You can also enter its image ID.',
  'Añade los enlaces de compra y escucha.': 'Add purchase and listening links.',
  'Código de la carátula': 'Cover image ID', 'Link para comprar': 'Purchase link', 'Link para escuchar': 'Listening link',
  'Créditos': 'Credits', 'Un crédito por línea: <code>Mastering__ Beau Thomas</code>.': 'One credit per line, for example <code>Mastering__ Beau Thomas</code>.',
  'Material de portada': 'Cover media', 'Arte propio reemplaza la carátula.': 'Custom artwork replaces the cover image.',
  'Video y póster son opcionales.': 'Video and poster are optional.',
  'En la grieta, <code>*</code> separa ambos grupos.': 'In the ticker, <code>*</code> separates the two groups.',
  'Texto de la grieta': 'Ticker text', 'Video': 'Video', 'Arte de portada': 'Cover artwork',
  'arte propio': 'custom artwork', 'la carátula de Bandcamp': 'Bandcamp cover image',
  'este lanzamiento': 'this release', 'Este lanzamiento': 'This release',
  'Deshacer': 'Undo', 'Leyendo Bandcamp…': 'Reading Bandcamp…',
  'Hay una versión más reciente. Tu copia local sigue disponible.': 'A newer version is available. Your local copy is still available.',
  'Recuperar mi copia': 'Restore my copy', 'Descartar mi copia': 'Discard my copy',
  'Otro lanzamiento': 'Another release', 'Elegir lanzamiento…': 'Choose a release…',
  'Sin carátula: añade arte abajo.': 'No cover image: add artwork below.',
  'No hay lanzamientos con imagen': 'No releases with images', 'No hay lanzamientos disponibles': 'No releases available',
  'Sin lanzamiento seleccionado': 'No release selected', 'Escoger otro lanzamiento': 'Choose another release',
  'Editar selección': 'Edit selection', 'Elegir lanzamiento': 'Choose a release', 'En el aleatorio': 'In random mode',
  'Selecciona el lanzamiento que verá el sitio.': 'Select the release to show on the site.',
  'Usa su carátula o añade arte propio abajo.': 'Use its cover image or add custom artwork below.',
  'Selecciona los lanzamientos que pueden aparecer.': 'Select the releases that may appear.',
  'Solo aparecen lanzamientos visibles con imagen.': 'Only visible releases with images can appear.',
  'Selecciona un lanzamiento arriba.': 'Select a release above.', 'Abrir su ficha →': 'Open its release →',
  'Editar →': 'Edit →', 'Sacar del video': 'Extract from video', 'Póster del video': 'Video poster',
  'Preparando fotogramas…': 'Preparing video frames…', 'Subiendo póster…': 'Uploading poster…',
  'Subir…': 'Upload…', 'listo': 'ready', 'reemplazado': 'replaced', 'Sin cambios.': 'No changes.',
  'Artículos': 'Articles', 'Añadir artículo': 'Add article', 'Vista previa de imagen': 'Image preview',
  'Grieta': 'Ticker',
  'Imagen del highlight': 'Highlight image', 'Una URL directa de imagen o un archivo propio.': 'Enter a direct image URL or upload a file.',
  'Artículo': 'Article', 'Etiqueta': 'Label', 'Link ↗': 'Link ↗', 'Texto': 'Text',
  'Sin contenido': 'No content', 'Sin artículo seleccionado': 'No article selected',
  'Artículo sin título': 'Untitled article', 'Subir artículo': 'Move article up', 'Bajar artículo': 'Move article down', 'Cerrar artículo': 'Close article', 'Cerrar ↑': 'Close ↑', 'Enlace del artículo': 'Article link', 'Extracto del artículo': 'Article excerpt',
  'Título del artículo': 'Article title', 'Link externo': 'External link', 'Visible': 'Visible', 'Oculto': 'Hidden',
  'Eliminar artículo': 'Delete article', 'Escribe el texto o extracto…': 'Write text or an excerpt…',
  'Contraseña incorrecta.': 'Incorrect password.', 'Escribe la contraseña.': 'Enter your password.',
  'Demasiados intentos. Espera unos minutos.': 'Too many attempts. Wait a few minutes.',
  'Falta configuración del panel.': 'The Studio is not configured.', 'No se pudo entrar.': 'Could not sign in.',
  'sesión vencida': 'session expired', 'no se pudo subir': 'could not upload',
  'fallo de conexión': 'connection error', 'Guardado. El sitio se actualizará en breve.': 'Saved. The site will update shortly.',
  'Corrige los campos marcados.': 'Correct the highlighted fields.',
  'Hay una versión más reciente. Recarga antes de guardar.': 'A newer version is available. Reload before saving.',
  'No hay cambios pendientes.': 'No pending changes.', 'Guardando…': 'Saving…', 'guardando…': 'saving…',
  'Guardado': 'Saved', 'guardado': 'saved', 'Guardar cambios': 'Save changes',
  'Ver catálogo en lista': 'View catalog as list', 'Ver catálogo en cuadrícula': 'View catalog as grid',
  'Ver lista': 'View list', 'Ver cuadrícula': 'View grid',
  'Buscar o crear artista…': 'Search or create an artist…',
  'Artistas disponibles': 'Available artists',
  'Poner el cuadro de': 'Use frame at',
  'ID de imagen de Bandcamp': 'Bandcamp image ID', 'URL de compra': 'Purchase URL',
  'URL para escuchar': 'Listening URL', 'La fecha se añade desde el campo Fecha.': 'Add the date in the Date field.',
  'Texto para la grieta': 'Ticker text',
  'Rol__ Nombre': 'Role__ Name',
  'No se pudo leer el repo:': 'Could not read the repository:',
  'URL o ruta de imagen': 'Image URL or path', 'URL de destino': 'Destination URL',
  'no se pudo leer la duración del video': 'could not read the video duration',
  'el navegador no pudo leer el video': 'the browser could not read the video',
  'este video no se puede leer desde aquí; sube el póster a mano': 'this video cannot be read here; upload the poster manually',
  'no se pudo abrir el video': 'could not open the video',
};
